(() => {
  'use strict';
  const file = location.pathname.split('/').pop().replace('.html','') || 'index';
  const pageNames = {'product-details':'Product details',checkout:'Checkout',payment:'Payment',success:'Order confirmed',support:'Support',about:'About us',terms:'Terms & conditions',journals:'Journals',careers:'Careers',affiliate:'Affiliate programme',press:'Press',faq:'FAQ',contact:'Contact',privacy:'Privacy policy',returns:'Returns & refunds',cookies:'Cookie guidelines',delivery:'Delivery information'};
  document.title = `${pageNames[file] || 'Store'} | ApnaMart`;
  const root = document.querySelector('#pageContent');
  const pageNav = document.querySelector('.page-nav');
  const pageNavLinks = document.querySelector('.page-nav-links');
  if (pageNav && pageNavLinks) {
    const menuToggle = document.createElement('button');
    menuToggle.type = 'button';
    menuToggle.className = 'page-menu-toggle';
    menuToggle.setAttribute('aria-label', 'Open navigation menu');
    menuToggle.setAttribute('aria-controls', 'innerPageMenu');
    menuToggle.setAttribute('aria-expanded', 'false');
    menuToggle.innerHTML = '<span></span><span></span><span></span>';
    pageNavLinks.id = 'innerPageMenu';
    pageNav.insertBefore(menuToggle, pageNav.querySelector('.cart-link'));
    const closeMenu = () => {
      pageNavLinks.classList.remove('mobile-open');
      menuToggle.classList.remove('active');
      menuToggle.setAttribute('aria-expanded', 'false');
      menuToggle.setAttribute('aria-label', 'Open navigation menu');
    };
    menuToggle.addEventListener('click', () => {
      const open = pageNavLinks.classList.toggle('mobile-open');
      menuToggle.classList.toggle('active', open);
      menuToggle.setAttribute('aria-expanded', String(open));
      menuToggle.setAttribute('aria-label', open ? 'Close navigation menu' : 'Open navigation menu');
    });
    pageNavLinks.addEventListener('click', e => { if (e.target.closest('a')) closeMenu(); });
    document.addEventListener('click', e => { if (!pageNav.contains(e.target)) closeMenu(); });
    document.addEventListener('keydown', e => { if (e.key === 'Escape') { closeMenu(); menuToggle.focus(); } });
  }
  const money = value => `₹${value.toLocaleString('en-IN')}`;
  const storage = {getItems(){try{const value=JSON.parse(localStorage.getItem('apnamart-cart-items')||'[]');return Array.isArray(value)?value:[]}catch{return[]}},setItems(value){try{localStorage.setItem('apnamart-cart-items',JSON.stringify(value));localStorage.setItem('apnamart-cart',String(value.reduce((sum,item)=>sum+item.quantity,0)))}catch{}}};
  let cartItems = storage.getItems();
  let cart = cartItems.reduce((sum,item)=>sum+item.quantity,0);
  const cartSubtotal = cartItems.reduce((sum,item)=>sum+(item.price*item.quantity),0);
  const deliveryCharge = cartSubtotal === 0 || cartSubtotal >= 499 ? 0 : 49;
  const cartTax = Math.round(cartSubtotal*.05);
  const orderTotal = cartSubtotal + deliveryCharge + cartTax;
  const updateCart = () => document.querySelectorAll('[data-cart-count]').forEach(el => el.textContent = cart);
  const hero = (kicker,title,copy) => `<section class="page-hero"><div class="container-fluid px-4 px-lg-5"><span class="page-kicker">${kicker}</span><h1 class="mt-3 mb-4">${title}</h1><p class="mb-0">${copy}</p></div></section>`;
  const summary = () => `<aside class="white-card p-4"><h3 class="h5 fw-bold mb-4">Order summary</h3>${cartItems.length?cartItems.map(item=>`<div class="d-flex gap-3 mb-3"><img src="${item.image}" width="64" height="64" style="object-fit:contain" alt=""><div class="flex-grow-1"><strong>${item.name}</strong><div class="small text-muted">Quantity ${item.quantity}</div></div><strong>${money(item.price*item.quantity)}</strong></div>`).join(''):'<div class="soft-card p-3 mb-3 text-muted">Your basket is empty. <a href="index.html">Continue shopping</a></div>'}<div class="summary-row"><span>Subtotal</span><strong>${money(cartSubtotal)}</strong></div><div class="summary-row"><span>Delivery</span><strong class="text-success">${deliveryCharge?money(deliveryCharge):'Free'}</strong></div><div class="summary-row"><span>Tax</span><strong>${money(cartTax)}</strong></div><div class="summary-row total"><span>Total</span><span>${money(orderTotal)}</span></div><p class="small text-muted mt-3 mb-0">Secure checkout · Easy returns · Quality guaranteed</p></aside>`;
  const info = {
    about:{k:'Our story',t:'Groceries rooted in everyday India.',c:'ApnaMart is a friendly neighborhood marketplace built to make quality essentials simpler, faster and more dependable for every household.',cards:[['Fresh by default','We work with trusted growers and local suppliers to keep everyday food genuinely fresh.'],['Fair prices','Clear pricing and useful offers—without confusing conditions or hidden surprises.'],['Made for families','Our service is designed around real routines, from weekly baskets to last-minute needs.']]},
    terms:{k:'Legal',t:'Terms & conditions',c:'These dummy terms explain the basic rules for using the ApnaMart demonstration storefront.',cards:[['Using ApnaMart','You must provide accurate information and use the service only for lawful personal shopping.'],['Orders & pricing','Demo prices and inventory may change. An order is confirmed only after successful payment.'],['Account responsibility','Keep account details secure and contact support if you notice unauthorized activity.']]},
    journals:{k:'From the market',t:'ApnaMart journals',c:'Stories, practical food guides and ideas for making everyday meals fresher and easier.',cards:[['Seasonal produce guide','A simple guide to choosing flavorful fruits and vegetables this month.'],['The smarter pantry','Ten versatile staples that make quick weekday cooking easier.'],['Meet our growers','How patient farming and shorter supply chains improve freshness.']]},
    careers:{k:'Join the team',t:'Build a better everyday market.',c:'We are creating thoughtful commerce for millions of household moments. Explore dummy opportunities across product, operations and customer experience.',cards:[['Frontend Engineer','Build fast, accessible shopping experiences for web and mobile.'],['Category Manager','Shape relevant assortments with suppliers and customer insight.'],['Customer Champion','Turn questions and problems into moments of genuine trust.']]},
    affiliate:{k:'Partner with us',t:'Grow with ApnaMart.',c:'Our affiliate programme helps creators and community partners earn rewards by introducing shoppers to useful everyday products.',cards:[['Simple referrals','Share a trackable ApnaMart link through your approved channels.'],['Transparent rewards','View dummy clicks, orders and commissions from one dashboard.'],['Partner support','Get campaign ideas, seasonal assets and a dedicated help channel.']]},
    press:{k:'Newsroom',t:'ApnaMart in the news.',c:'Dummy announcements, company facts and media resources for stories about our marketplace.',cards:[['ApnaMart expands fresh delivery','The service introduces same-day fresh baskets across three new cities.'],['Less packaging, more care','A new reusable crate pilot reduces single-use packaging in weekly orders.'],['Media enquiries','Contact press@apnamart.example for dummy interviews and brand resources.']]},
    privacy:{k:'Your data',t:'Privacy policy',c:'This demonstration policy describes how ApnaMart may handle account and shopping information.',cards:[['Information we use','Contact, delivery and order details help provide and improve the service.'],['Your choices','You may request access, correction or deletion of eligible personal information.'],['Security','Reasonable technical and organizational safeguards protect stored information.']]},
    returns:{k:'Shop confidently',t:'Returns & refunds',c:'If something is not right, our dummy return process is designed to be straightforward.',cards:[['Fresh items','Report damaged or unsatisfactory fresh products within 24 hours of delivery.'],['Packaged goods','Eligible unopened items may be returned within seven days with proof of purchase.'],['Refund timing','Approved refunds normally appear in the original payment method within 5–7 days.']]},
    cookies:{k:'Your preferences',t:'Cookie guidelines',c:'Cookies help this demo remember baskets, preferences and basic site usage.',cards:[['Essential cookies','Required for sign-in, cart state, security and checkout functions.'],['Analytics cookies','Help understand general usage so the experience can be improved.'],['Managing cookies','Use your browser controls to remove or block non-essential cookies.']]},
    delivery:{k:'From shelf to door',t:'Delivery information',c:'Choose a convenient slot and follow your dummy ApnaMart order from packing to doorstep.',cards:[['Delivery windows','Available slots vary by area, order volume and product availability.'],['Fresh handling','Chilled and fresh items are packed separately to preserve quality.'],['At your doorstep','Check your order at delivery and report missing or damaged items promptly.']]}
  };
  const renderInfo = data => `${hero(data.k,data.t,data.c)}<section class="content-section"><div class="container-fluid px-4 px-lg-5"><div class="info-grid">${data.cards.map((x,i)=>`<article class="soft-card info-card"><span class="page-kicker">0${i+1}</span><h3 class="mt-3">${x[0]}</h3><p class="text-muted mb-0">${x[1]}</p></article>`).join('')}</div><div class="white-card p-4 p-lg-5 mt-4"><h2 class="h3 fw-bold">Need more information?</h2><p class="text-muted">This is demonstration content for the ApnaMart storefront. Our support team can help with general questions.</p><a class="btn btn-apna" href="support.html">Visit support</a></div></div></section>`;
  const product = () => `${hero('Fresh pick','Sunstar fresh melon juice','Naturally refreshing, carefully packed, and delivered with your everyday essentials.')}<section class="content-section"><div class="container-fluid px-4 px-lg-5"><div class="row g-5 align-items-center"><div class="col-lg-6"><div class="product-image-panel"><img src="assets/images/apnamart-product-thumb-1.png" alt="Sunstar fresh melon juice"></div></div><div class="col-lg-6"><span class="tag-pill">Fresh arrival</span><h2 class="display-6 fw-bold mt-3">Sunstar Fresh Melon Juice</h2><div class="d-flex gap-3 align-items-center my-3"><span class="rating-pill">★ 4.8 · 126 reviews</span><span class="text-muted">1 litre</span></div><div class="d-flex gap-3 align-items-end"><span class="price">₹149</span><span class="old-price">₹199</span><span class="text-success fw-bold">25% off</span></div><p class="text-muted my-4">A bright blend made with ripe melon and no artificial colours. Serve chilled for breakfast, after a workout, or whenever your day needs a fresh lift.</p><div class="d-flex flex-wrap gap-3"><div class="qty-control"><button data-qty-minus>−</button><input data-qty value="1" readonly aria-label="Quantity"><button data-qty-plus>+</button></div><button class="btn btn-apna flex-grow-1" data-add-cart>Add to basket</button></div><div class="row g-3 mt-4"><div class="col-6"><div class="soft-card p-3"><strong>Free delivery</strong><div class="small text-muted">On orders over ₹499</div></div></div><div class="col-6"><div class="soft-card p-3"><strong>Quality promise</strong><div class="small text-muted">Easy replacement</div></div></div></div></div></div></div></section>`;
  const checkout = () => `${hero('Checkout','Where should we deliver?','Add your delivery details and choose a convenient slot.')}<section class="content-section"><div class="container-fluid px-4 px-lg-5"><div class="checkout-steps mb-4"><span class="checkout-step active">1 Delivery</span><span>→</span><span class="checkout-step">2 Payment</span><span>→</span><span class="checkout-step">3 Complete</span></div><div class="row g-4"><div class="col-lg-7"><form class="white-card p-4 p-lg-5" data-next="payment.html"><h2 class="h4 fw-bold mb-4">Delivery details</h2><div class="row g-3"><div class="col-md-6"><label class="form-label">Full name</label><input class="form-control" required placeholder="Enter your full name"></div><div class="col-md-6"><label class="form-label">Mobile number</label><input class="form-control" required inputmode="tel" placeholder="Enter your mobile number"></div><div class="col-12"><label class="form-label">Address</label><input class="form-control" required placeholder="Enter your delivery address"></div><div class="col-md-6"><label class="form-label">City</label><input class="form-control" required placeholder="Enter your city"></div><div class="col-md-3"><label class="form-label">State</label><select class="form-select"><option>Karnataka</option><option>Maharashtra</option><option>Delhi</option></select></div><div class="col-md-3"><label class="form-label">PIN code</label><input class="form-control" required inputmode="numeric" placeholder="Enter PIN code"></div><div class="col-12"><label class="form-label">Delivery slot</label><select class="form-select"><option>Today · 6 PM–8 PM</option><option>Tomorrow · 8 AM–10 AM</option><option>Tomorrow · 12 PM–2 PM</option></select></div></div><button class="btn btn-apna w-100 mt-4" type="submit">Continue to payment</button></form></div><div class="col-lg-5">${summary()}</div></div></div></section>`;
  const payment = () => `${hero('Secure payment','Choose how to pay.','Your dummy transaction is protected and no real charge will be made.')}<section class="content-section"><div class="container-fluid px-4 px-lg-5"><div class="checkout-steps mb-4"><span class="checkout-step">1 Delivery</span><span>→</span><span class="checkout-step active">2 Payment</span><span>→</span><span class="checkout-step">3 Complete</span></div><div class="row g-4"><div class="col-lg-7"><form class="white-card p-4 p-lg-5" data-next="success.html"><h2 class="h4 fw-bold mb-4">Payment method</h2><div class="form-check soft-card p-3 ps-5 mb-3"><input class="form-check-input" type="radio" name="pay" id="upi" checked><label class="form-check-label fw-bold" for="upi">UPI <span class="d-block small text-muted fw-normal">Google Pay, PhonePe, Paytm or any UPI app</span></label></div><div class="form-check soft-card p-3 ps-5 mb-3"><input class="form-check-input" type="radio" name="pay" id="card"><label class="form-check-label fw-bold" for="card">Credit or debit card <span class="d-block small text-muted fw-normal">Visa, Mastercard and RuPay</span></label></div><div class="form-check soft-card p-3 ps-5"><input class="form-check-input" type="radio" name="pay" id="cod"><label class="form-check-label fw-bold" for="cod">Cash on delivery <span class="d-block small text-muted fw-normal">Pay when your order arrives</span></label></div><button class="btn btn-apna w-100 mt-4" type="submit" ${cartItems.length?'':'disabled'}>Pay ${money(orderTotal)}</button></form></div><div class="col-lg-5">${summary()}</div></div></div></section>`;
  const success = () => `${hero('Order confirmed','Your groceries are on the way.','Thanks for shopping with ApnaMart. We have received your dummy order.')}<section class="content-section"><div class="container-fluid px-4 px-lg-5"><div class="white-card text-center p-4 p-lg-5 mx-auto" style="max-width:760px"><div class="success-mark">✓</div><h2 class="h2 fw-bold mt-4">Thank you for your order!</h2><p class="text-muted">Order <strong>#APNA260719</strong> will arrive today between 6 PM and 8 PM.</p><div class="soft-card p-4 text-start my-4"><div class="summary-row"><span>Delivery address</span><strong>Home</strong></div><div class="summary-row"><span>Payment</span><strong>Paid · UPI</strong></div><div class="summary-row"><span>Order total</span><strong>${money(orderTotal)}</strong></div></div><a class="btn btn-apna" href="index.html">Continue shopping</a> <a class="btn btn-outline-dark" href="support.html">Get help</a></div></div></section>`;
  const support = () => `${hero('We are here to help','How can we support you?','Find quick answers or send our dummy customer care team a message.')}<section class="content-section"><div class="container-fluid px-4 px-lg-5"><div class="row g-4 mb-5"><div class="col-md-4"><div class="soft-card p-4 h-100"><span class="support-icon">☎</span><h3 class="h5 fw-bold mt-3">Call us</h3><p class="text-muted small">1800-APNA-MART<br>8 AM–10 PM daily</p></div></div><div class="col-md-4"><div class="soft-card p-4 h-100"><span class="support-icon">✉</span><h3 class="h5 fw-bold mt-3">Email</h3><p class="text-muted small">help@apnamart.example<br>Replies within 24 hours</p></div></div><div class="col-md-4"><div class="soft-card p-4 h-100"><span class="support-icon">◉</span><h3 class="h5 fw-bold mt-3">Live chat</h3><p class="text-muted small">Chat with our dummy assistant<br>Average wait: 2 minutes</p></div></div></div><div class="row g-4"><div class="col-lg-6"><form class="white-card p-4" data-message><h2 class="h4 fw-bold">Send a message</h2><input class="form-control my-3" required placeholder="Enter your email address"><select class="form-select mb-3"><option>Order issue</option><option>Returns and refunds</option><option>Product question</option></select><textarea class="form-control mb-3" rows="5" required placeholder="Describe your request"></textarea><button class="btn btn-apna" type="submit">Submit request</button><p class="text-success small mt-3 mb-0" data-form-status></p></form></div><div class="col-lg-6"><div class="accordion" id="faq"><h2 class="h4 fw-bold mb-3">Popular questions</h2>${['Where is my order?','How do I request a refund?','Can I change my delivery slot?'].map((q,i)=>`<div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button ${i?'collapsed':''}" data-bs-toggle="collapse" data-bs-target="#answer${i}">${q}</button></h3><div id="answer${i}" class="accordion-collapse collapse ${i?'':'show'}" data-bs-parent="#faq"><div class="accordion-body text-muted">This is a helpful dummy answer. Open your order details or contact our team for assistance.</div></div></div>`).join('')}</div></div></div></div></section>`;
  const faq = () => {
    const questions = [
      ['orders','How do I place an order?','Browse the store, choose a quantity, select Add to Cart, and open your basket to continue through delivery and payment.'],
      ['payments','Which payment methods are accepted?','You can choose UPI, major credit or debit cards, or cash on delivery during checkout. This demonstration does not process real payments.'],
      ['delivery','Can I schedule my delivery?','Yes. Available delivery windows appear at checkout, where you can select the slot that works best for you.'],
      ['orders','Can I change or cancel an order?','Contact support as soon as possible. Changes are available only before the store begins packing your order.'],
      ['delivery','How can I track my order?','Once an order is confirmed, its latest packing and delivery status appears in your order details.'],
      ['products','What happens if an item is unavailable?','We will notify you before delivery. You can accept a suitable replacement or receive a refund for the unavailable item.'],
      ['returns','How do returns and refunds work?','Report fresh-item issues within 24 hours. Eligible packaged goods can be returned within seven days with proof of purchase.'],
      ['account','How can I contact ApnaMart support?','Visit our support page to send a message, start a chat, or find the customer-care contact details.']
    ];
    return `${hero('Help centre','Answers for easier everyday shopping','Find clear guidance about ordering, delivery, payments, products and returns.')}<section class="faq-section"><div class="container-fluid px-4 px-lg-5"><div class="faq-search-panel"><div class="faq-search-copy"><span class="faq-search-icon" aria-hidden="true">?</span><div><h2>How can we help?</h2><p>Search the most common ApnaMart questions.</p></div></div><label class="faq-search"><span aria-hidden="true">⌕</span><input type="search" data-faq-search placeholder="Search help topics" aria-label="Search frequently asked questions"></label></div><div class="faq-category-grid" aria-label="FAQ categories">${[['▣','Orders','Placing and updating orders'],['⌖','Delivery','Slots, tracking and arrival'],['₹','Payments','Payment options and charges'],['↻','Returns','Replacements and refunds']].map(x=>`<article class="faq-category-card"><span>${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join('')}</div><div class="row g-4 g-lg-5 align-items-start"><div class="col-lg-4"><aside class="faq-aside"><span class="page-kicker">Popular questions</span><h2>Everything you need to know.</h2><p>Browse the answers or search above. If your question is not listed, our customer-care team is ready to help.</p><a class="btn btn-apna" href="support.html">Contact support <span aria-hidden="true">→</span></a><div class="faq-response"><span></span><strong>Support available daily</strong><small>8 AM–10 PM</small></div></aside></div><div class="col-lg-8"><div class="accordion faq-accordion" id="fullFaq">${questions.map((x,i)=>`<div class="accordion-item" data-faq-item data-faq-text="${(x[1]+' '+x[2]+' '+x[0]).toLowerCase()}"><h3 class="accordion-header"><button class="accordion-button ${i?'collapsed':''}" type="button" data-bs-toggle="collapse" data-bs-target="#faq${i}" aria-expanded="${i?'false':'true'}" aria-controls="faq${i}"><span class="faq-number">${String(i+1).padStart(2,'0')}</span><span>${x[1]}</span></button></h3><div id="faq${i}" class="accordion-collapse collapse ${i?'':'show'}" data-bs-parent="#fullFaq"><div class="accordion-body">${x[2]}</div></div></div>`).join('')}<div class="faq-empty" data-faq-empty><span>⌕</span><h3>No matching answers</h3><p>Try another search or contact our support team.</p><a href="support.html">Visit support</a></div></div></div></div></div></section>`;
  };
  const routes = { 'product-details':product, checkout, payment, success, support, faq, contact:support };
  if (root) root.innerHTML = routes[file] ? routes[file]() : info[file] ? renderInfo(info[file]) : renderInfo(info.about);
  document.addEventListener('click', e => { if(e.target.matches('[data-qty-plus]')) document.querySelector('[data-qty]').value++; if(e.target.matches('[data-qty-minus]')) document.querySelector('[data-qty]').value=Math.max(1,document.querySelector('[data-qty]').value-1); if(e.target.matches('[data-add-cart]')){const quantity=Number(document.querySelector('[data-qty]').value);const id='sunstar-fresh-melon-juice';const existing=cartItems.find(item=>item.id===id);if(existing)existing.quantity+=quantity;else cartItems.push({id,name:'Sunstar Fresh Melon Juice',image:'assets/images/apnamart-product-thumb-1.png',price:149,quantity});storage.setItems(cartItems);cart=cartItems.reduce((sum,item)=>sum+item.quantity,0);updateCart();e.target.textContent='Added to basket ✓';setTimeout(()=>location.href='checkout.html',500);}});
  document.addEventListener('submit', e => { const next=e.target.dataset.next; if(next){e.preventDefault();location.href=next;} if(e.target.matches('[data-message]')){e.preventDefault();e.target.querySelector('[data-form-status]').textContent='Thanks! Your request APNA-1042 has been submitted.';e.target.reset();}});
  const faqSearch = document.querySelector('[data-faq-search]');
  if (faqSearch) faqSearch.addEventListener('input', e => {
    const query = e.target.value.trim().toLowerCase();
    let visible = 0;
    document.querySelectorAll('[data-faq-item]').forEach(item => {
      const matches = !query || item.dataset.faqText.includes(query);
      item.hidden = !matches;
      if (matches) visible++;
    });
    document.querySelector('[data-faq-empty]').classList.toggle('show', visible === 0);
  });
  if(file==='success'){storage.setItems([]);cart=0;}
  updateCart();
})();
